// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXjEr8BHXtw1fl7kYc9T_FW2SiD0TpgA8',
    appId: '1:723398972738:web:50bd3eac6019ae63d264db',
    messagingSenderId: '723398972738',
    projectId: 'debugproject-a0367',
    authDomain: 'debugproject-a0367.firebaseapp.com',
    storageBucket: 'debugproject-a0367.appspot.com',
    measurementId: 'G-2BQ0Z4N197',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR7Ke6xD0du0-9wybd0rjNIchc8G4uuXU',
    appId: '1:723398972738:android:c7113e0cc7ca54b7d264db',
    messagingSenderId: '723398972738',
    projectId: 'debugproject-a0367',
    storageBucket: 'debugproject-a0367.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5y7BsBtscyGGApp8qO6URhJiDvwntn7o',
    appId: '1:723398972738:ios:4d29b6d6a6eca52fd264db',
    messagingSenderId: '723398972738',
    projectId: 'debugproject-a0367',
    storageBucket: 'debugproject-a0367.appspot.com',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5y7BsBtscyGGApp8qO6URhJiDvwntn7o',
    appId: '1:723398972738:ios:4d29b6d6a6eca52fd264db',
    messagingSenderId: '723398972738',
    projectId: 'debugproject-a0367',
    storageBucket: 'debugproject-a0367.appspot.com',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXjEr8BHXtw1fl7kYc9T_FW2SiD0TpgA8',
    appId: '1:723398972738:web:bf2ee568a453239ad264db',
    messagingSenderId: '723398972738',
    projectId: 'debugproject-a0367',
    authDomain: 'debugproject-a0367.firebaseapp.com',
    storageBucket: 'debugproject-a0367.appspot.com',
    measurementId: 'G-M9LV810YTK',
  );
}
